### ISSUE TITLE
Contrastive Explanation Method - Black Box Models 

### ISSUE THREAD

**Issue by firmai** [SeldonIO/alibi#184]
Any way in which non-nn bb methods can be used for CEM,. https://docs.seldon.io/projects/alibi/en/stable/methods/CEM.html

**Comment by arnaudvl** [comment]
Hi @firmai . Short answer: yes. The Iris example in the docs illustrates this: https://docs.seldon.io/projects/alibi/en/stable/examples/cem_iris.html#Use-numerical-gradients-in-CEM. For numerical gradient optimisation, the method only requires access to a predict function which can take numpy arrays as an input and outputs probabilities over the classes. We are also thinking about using genetic algorithms to make the black box optimisation part more practical instead of computing numerical gradients.

**Comment by firmai** [comment]
Thanks for the answer @arnaudvl it seems I would suffer the same issue as in https://github.com/SeldonIO/alibi/issues/172#issuecomment-592266745

If this can be solved then LightGBM would work for both systems.

**Comment by arnaudvl** [comment]
Thanks @firmai  for the Colab notebook to check your issue out. I quickly skimmed the notebook and noticed that the output of the lightgbm predict function for the binary classification problem only returns the class probabilities for 1 class ([0.31371936]) instead of the probabilities over both classes ([0.31371936, 0.68628064]). The prediction function passed to the CounterFactualProto should return probabilities over each class. You could provide a slightly adjusted lightgbm prediction function that makes sure both class probabilities are returned.

**Comment by arnaudvl** [comment]
Hi @firmai , could you confirm whether that solved the issue? Thanks!

**Comment by firmai** [comment]
Yes, sorry, your solution worked thanks!
