### ISSUE TITLE
Error in code - variable referenced before assignment 

### ISSUE THREAD

**Issue by miouantoinette** [SeldonIO/alibi#210]
I ran into the following error

```
No appropriate lambda range found, try decreasing lam_init
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/alibi/explainers/counterfactual.py", line 522, in _minimize_loss
    lb_ix = np.where(cf_count > 0)[0][1]  # take the second order of magnitude with some CFs as lower-bound
IndexError: index 1 is out of bounds for axis 0 with size 0
```

It's in the counterfactuals.py file, line 526 (the relevant code is blow). The variable lb_ix is only defined in 'try' code (line 522), which causes a problem. 
`        try:
            lb_ix = np.where(cf_count > 0)[0][1]  # take the second order of magnitude with some CFs as lower-bound
            # TODO robust?
        except IndexError:
            logger.exception('No appropriate lambda range found, try decreasing lam_init')
        lam_lb = np.ones(self.batch_size) * lams[lb_ix]`

**Comment by jklaise** [comment]
The error happens because the first thing the algorithm does is to find a  suitable `lambda` (the coefficient in front of the distance part of the loss), this is done by starting with a "small" value of `lam_init` and gradually increasing it on an exponential scale (controlled by `max_lam_steps`). The fact that this error occurs suggests that for your use case you need to set `lam_init` to be smaller than the default value. Using a too high value looks like causes the model to focus on instances very close to the original instance such that the model can't find any counterfactuals.
