### ISSUE TITLE
ValueError: Quantiles array should be sorted! & Catgorical features

### ISSUE THREAD

**Issue by Dola47** [SeldonIO/alibi#221]
Dear all,

I am trying to use Anchor to interpret my Tabular data

I would like to note that I got an error stating that the Quantiles array should be sorted, after I call explainer.fit on my dataset array.  Any idea how to overcome this error?

Moreover, for the categorical features, I actually preprocess my dataset so I process the categorical features and one hot encode them. Afterwards, I pass a pandas dataframe of this processed dataset to the explainer.fit. So, all of the features should be treated as continous features in such a case. May that cause any problem? Should I instead pass the initial dataset before processing and indicate the keys and categories of each features?

**Comment by jklaise** [comment]
The `AnchorTabular` explainer currently expects a "raw" tabular dataset, i.e. before one-hot encoding any categorical features. So as you say, you should pass in the initial dataset before processing, define the model function so that it takes in as input the initial dataset (see an example here https://docs.seldon.io/projects/alibi/en/latest/examples/anchor_tabular_adult.html), and finally pass in a dictionary `categorical_names` which indicates which columns are categorical feature and what categories are available for each categorical feature (you can use `alibi.utils.data.gen_category_map` to create this automatically from a pandas dataframe or numpy array.

Also note that we work with numpy arrays instead of pandas dataframes, so your model has to take numpy arrays as input.

I'll keep this issue open as we could be more explicit in the docstrings.

**Comment by Dola47** [comment]
@jklaise  Thanks a lot for your response.

Regarding the categorical features, does the same hold for the other types of the Explainers as well, for example for the ShapExplainer?

That is not really so supportive, because I have in my framework more than 11 preprocessors, and it is painful to extract the OnehotEncoder out of them, because some of them depend on the results of the other processors :(

**Comment by jklaise** [comment]
1. As a minimum we support numpy arrays as input across all explainers and when categorical variables are in play then they should not be one-hot encoded, although there are exceptions (e.g. `CounterFactualProro` can take one-hot encoded data). With time we hope to support more input formats. `KernelShap` also supports pandas dataframes, but I think you still need to provide categorical features as one per column @alexcoca ?

I would like to understand your use case a bit more, you can always have the one-hot encoder (or any preprocessor/transformer) as part of the model itself, e.g. something like `predict_fn = lambda x: clf.predict(transformer.transform(x))` where `x` is the raw data and `transformer` could be your pre-processing pipeline, all explainers should work with this pattern. Of course the situation is different if you have lots of pre-trained models which take in encoded data or if your data comes in as encoded already.

2. Yes, I believe this issue will go away with the correct input.

3. The explainer will not do any encoding itself, the inputs should be exactly the same as for the underlying model, i.e. if one-hot encoding is done in the model then the model prediction function should be defined as `predict_fn` in point 1. As for the explanation of `AnchorTabular` itself - it converts numerical features into bins and leaves categorical values as is, so e.g. an explanation might be something like `20 < age < 30 AND marital_status"divorced"`.

**Comment by Dola47** [comment]
@jklaise 

Well, I am using an Xgbooster as my model. I think the way I am building my predict function is quite different from the one you mentioned. I am assuming that internally from the explainer the instance that needs to be explained will be passed to the predict function, so my predict function is adjusted to deal with a processed version of my data.

The way I am building my predict function is like that:
![Capture](https://user-images.githubusercontent.com/45386621/81810729-c5042a80-9523-11ea-9567-c78bf82a2a2a.PNG)

Where data is one of the instance of the processed dataset, self.features is the number of processed features. I create a batch out of them and sent them to the get_probabilities function.

The get_probabilities function is here:
![Capture1](https://user-images.githubusercontent.com/45386621/81810822-efee7e80-9523-11ea-8c6c-c452b53f02ae.PNG)

**Comment by alexcoca** [comment]
@jklaise, KernelShap should be able to deal with both, as per the examples. However, one has to be able to specify the `category_map` and `feature_names` correctly to the constructor if they want meaningful feature importances in the response.

**Comment by Dola47** [comment]
@alexcoca  What I got from your answer that even for example if the dataset submitted to the KernelExplainer, and the rows submitted to the shap_values is already processed and one hot encoded SHAP will work effectively. Am I right?

**Comment by alexcoca** [comment]
Hi @Dola47 ,

The `KernelShap` refers to the wrapper in this library, which has only an `explain` method and no `shap_value` method. If you pass an encoded background dataset to `fit`, then it will work if you also pass encoded data to explain. 

However, especially for encoded data, `KernelShap` will be very expensive computationally. We are in the process of wrapping the `TreeExplainer` from `shap`, so in the meantime I suggest you use it to obtain explanations efficiently.

If you want an Anchor explanation, you can add an additional method to your class that wraps your current code and can work well with the `AnchorTabular` explainer. This can roughly be as follows:

```python
def predict_wrapper(self, raw_data):
  
 # transform the data as required by `get_probabilities`
   data = self.transform(raw_data) 
   probabilities = self.predict_proba(data)

   return probabilities.values
```

All you need to do is to apply the same transformation as you would to the raw data so that it has the correct format for your model. Then just return the values of that data frame. 

You can then instantiate the explainer as
```
explainer = AnchorTabular(my_model.predict_wrapper, feature_names = ... , category_map = ...)
```

Another option, which I would expect to allow you to use your encoded data directly with the encoded categorical data would be to correctly specify the `feature_names` and `category_map` arguments to the constructor.

In particular:

- `feature_names` has to be of length equal to the dimension of your encoded data, and have string entries denoting the names of the variables. For example if you had categorical variables `sex` with two levels,  a continuous variable `age` and `occupation` with 3 levels in your raw data,  your feature vectorwould be something like `feature_names=['sex_0', 'sex_1', 'age', 'occupation_1', 'occupation_2', 
'occupation_3'])`
- follwing from the above the category map would have to have the following form
```python
{
0: ['Male'], 
1:['Female'], 
3:['Blue Collar']
4:['White Collar'],
5:['Other']
}
```
Again, I would advise against attemping this on the basis of computational time: anchors is a combinatorial search procedure with scales quite badly with the dimension so, to save time, it is just easier to transform the data inside the predict function wrapper as described above.

**Comment by Dola47** [comment]
@alexcoca  Thanks a lot for your valuable comment.  I will try to implement it.

However, I would like also to know in the Orginal KernelShap should I also specify the categorical features? Or it will working probably even if I passed it only with the processed data as well, and passed the shap_values with the processed data?

**Comment by alexcoca** [comment]
Hi @Dola47 ,

`KernelShap` would work even if you don't tell it which are the categorical variables, so long `background_data` input to `fit` and `X` input to explain are both encoded. 

For slightly better efficiency, I suggest you to specify the `group_names` and `groups` to `fit`. For the above example this can be done as:

```python
group_names = ['sex', 'age', 'occupation']
groups = [[0, [1], [2], [3, 4, 5]]
````

In this case, you will compute a shap value for each variable. If you don't specify the grouping you get a shap value for each dimension of the categorical variable (so `occupation` will have 3 shap values).

```

**Comment by Dola47** [comment]
@alexcoca  Totally agree with your answer thanks. Moreover, from the case of the original ShapKernel where should I define the categorical features in the shap_values or the KernelExplainer?

**Comment by alexcoca** [comment]
Hi @Dola47,

I'm afraid I do not understand what you mean in your first paragraph. I don't know what the _original ShapKernel_ is - our library has an object `KernelShap` that can be used to calculate the shap values. As explained in my previous answer, the only way `KernelShap` knows about the categorical variables is by the specification of `groups` or `group_names`. I don't really understand about "defining categorical feature in the shap_values or the KernelExplainer`. The `KernelExplainer`  is an object used internally by us and you should not be concerned with it. All you need to do is to `fit` the explainer as explained in the docstring, the documentation and my previous examples. 

Regarding the second point. Kernel shap returns an estimate of the shap values, where `xgboost` or the `TreeExplainer` configured with the same background dataset will return the exact quantities. Moreover, they return the exact quantities _efficiently_. So the latter algorithms are better. To make it clear, KernelShap doesn't use the LIME kernel, it has its own special kernel. Please see our documentation for details, but, in one sentence, the reason why KernelShap uses that kernel is to approximate a quantity that can be calculated _exactly_ for tree models.

**Comment by Dola47** [comment]
@alexcoca  Thanks a lot for your answers, they are very clear and precise thanks alot.4
I was actually meaning how to use the categorical features in the case of KernelShap the one from slundberg. Because I see that there we do not have any parameters for the categorical features.

I would like to know, what is actually being submitted to the predict_fn because I see it only accepts numpy array because I have currently the following error 
![Capture](https://user-images.githubusercontent.com/45386621/81828185-cb9d9c80-9539-11ea-908c-41e4b9618f1d.PNG)

I am assuming that the predict function will receive a row from the PandasDataFrame.

This is how I currently implement my predict function:
![Capture1](https://user-images.githubusercontent.com/45386621/81828272-e8d26b00-9539-11ea-943e-892f05ce697e.PNG)
 
Given that my dataset is actually a PandasDataset

**Comment by alexcoca** [comment]
Hi @Dola47 ,

**1. Difference between `alibi` `KernelShap` and `shap` KernelExplainer. Handing of categorical variables in `shap` **
As far as I know, the `shap` library does not have any special handling of categorical variables. We implemented grouping, as described above, following discussions in the `shap` library issues. This saves a tiny bit of computation time and gives you only 1 value for each categorical variable. Our `KernelShap` wrapper uses the same algorithms but makes sure that the encodings are treated as a single dimension as opposed to individidual dimensions when calculating the shap variables. To put is simply, instead of calculating `m` shap values for a categorical variable with `m` levels, we calculate just one.

**Comment by Dola47** [comment]
@alexcoca  Can you verify to me what is actually being submitted to the predict_fn as well?

**Comment by alexcoca** [comment]
@Dola47 , see updated comment.

**Comment by Dola47** [comment]
@alexcoca  From where this numpy array is instantiated? I need to know from where it exactly comes to know what columns I should attach during converting it to Dataframe? I do not know if this numpy array is processed or not?

**Comment by alexcoca** [comment]
Hi @Dola47, 

As the stack trace shows, `AnchorTabular` calls the predict function with a numpy array in line `678`. The input is in this case a dummy vector of zeros, which we use to test if the model returns probabilities or labels. This vector will have the length of the `feature_names` vector you passed in, so it should represent the raw data.

**Comment by alexcoca** [comment]
@Dola47 ,

I see that in your instanstiation of `AnchorTabular`, you have not passed the `categorical_names` argument. This means that all the variables will be discretized. Please specify a dictionary that contains the indices of the categorical variables as keys, and the human readable categorical levels as values. For our running example this would be:

```python
categorical_names = {
0: [Female, Male],
2: ['Blue Collar', 'White Collar' , 'Other']
}
```

The interpretation of that is that the raw data contains categorical variables `sex` and `occupation` in columns `0` and `2`, respectively. Moreover, it assumes that a `0` in column with index `0` represents a female and a `1` in the same column represents a male. Similarly, for column with index `2`, a `3` will represent `'Other'`. Note that `1` is missing since `age` is a continuous variable, which our explainer will discretize internally. Hence, for `AnchorTabular` it is important to make a distinction between categorical/continuous variables and this is done by correctly specifying the `feature_names` of the raw data and the `categorical_names`.

**Comment by Dola47** [comment]
@alexcoca  I really got currently all of your answers. Thanks a lot you are extremely helpful. Many many thanks. I will try to arrange now everything, I think it is not easy for me to use directly the raw data. I am sure, that I am going to face a lot of errors.  I will contact you back once I need a help.

Many thanks Alex.

**Comment by Dola47** [comment]
@alexcoca  For your third answer in this comment, it is related to working with AnchorExplainer after processing the dataset:
https://github.com/SeldonIO/alibi/issues/221#issuecomment-627974001.

If I understand correctly, I just build my category map such that it has the index of each of the categories of the OneHotEncoded features, and their names as well. 

For example one of my categorical features is: LineName and it has 3 categories HU9-A2, HU9-A3, and HU9-A5. Then I built the categorical map like the following:
![Capture](https://user-images.githubusercontent.com/45386621/81989422-7c409480-963d-11ea-9ab5-7d14ed99bf99.PNG)

If the above point is correct, then can you guess why I still have the same error as before. Given that, I followed all of your comments and the implementation should be correct.
![Capture2](https://user-images.githubusercontent.com/45386621/81989485-99756300-963d-11ea-9554-2bbd30d00e63.PNG)

**Comment by jklaise** [comment]
@Dola47 we don't recommend using the one-hot encoding for the raw data as this will simply not work well with the algorithm. Instead we suggest to use the raw data (before encoding) and use the `category_map` of this sort:

```python
category_map = {306: [LineName1, LineName2, LineName3],
                307: [TypeFamily1, TypeFamily2, TypeFamily3]
}
```
etc.

**Comment by Dola47** [comment]
@jklaise  Then I will try my best to adapt my framework to this case, but I getting a lot of errors from my framework.

I think the category_map should be built like that in such a case:
`category_map = {0: ['BhP-HU9-A2', 'BhP-HU9-A3', 'BhP-HU9-A5'],
                             319: [ 'ESP9.x-CP', 'ESP9.0-LE', 'ESP9.x-CE', 'ESP9.x-CB', 'ESP9.0/9.1-CU', 'ESP9.2/ESP9.3', 'ESP9-HEV X'],
}`

As my categories for the first feature `LineName` are:  `'BhP-HU9-A2', 'BhP-HU9-A3', 'BhP-HU9-A5'`

**Comment by jklaise** [comment]
@Dola47, yep that sounds correct!

**Comment by Dola47** [comment]
@jklaise @alexcoca 

I tried to use CEM, Counterfactual Instances, and Prototype Counterfactuals. However, when I pass my XGBoost model built internally in my framework, I get the following error.

![Capture](https://user-images.githubusercontent.com/45386621/82145223-95b62c00-9849-11ea-9505-9d64d2c9fddf.PNG)

I do not know if this is something specific only to the XGboost model, or because I am importing the model from my framework so it is not the default know Xgboost model, it is actually XgboostModel.ICdata.base.models?

**Comment by jklaise** [comment]
@Dola47 as the error message says, the model has to be a `Callable` function (or a TensorFlow/Keras model), so your model needs to be wrapped up as such (e.g. something like `lambda predict(x): model.predict(x)`. On a different note, I wouldn't recommend using the counterfactual based algorithms for tree based models because the explainers assume that the models are differentiable as they need to calculate gradients to work, there's an open issue for extending the methods to use gradient-free optimization #176 .

**Comment by Dola47** [comment]
@jklaise I think that I should instead of passing the model, just pass the model.predict_fn, Am I right?

**Comment by Dola47** [comment]
@jklaise @alexcoca 

I just tried to pass my Xgboost model predict function to the CEM explainer, and I got the following error.

I wonder if you can help me with that error?

If not, can you describe for me what I should do exactly to change my model into a callable model?  I think the main problem is that my framework used model is not known to the CEM explainer.

Here you will find a detailed screenshot of the error I am facing currently.
![Error from CEM](https://user-images.githubusercontent.com/45386621/82844844-5a1f0000-9ee2-11ea-934d-225bad8670bb.png)

**Comment by jklaise** [comment]
@Dola47 looks like some type mismatch with the arguments, what are the values of `beta` and `feature_range`?

Also note that we've updated guidance for the currently supported methods, the CEM whilst works on black-box models really expects a differentiable model due to the gradient based optimization so an xgboost model which is not differentiable will not work well: https://github.com/SeldonIO/alibi#supported-methods

**Comment by Dola47** [comment]
@jklaise  Thanks for mentioning that Xgboost will not work with CEM.
Can you mention what explanation methods should work with my Xgboost model, given that I have also categorical features?

**Comment by jklaise** [comment]
@Dola47 `AnchorTabular` and `TreeSHAP` should work best (to access `TreeSHAP` you would need to install the development version of alibi `pip install git+https://github.com/SeldonIO/alibi.git` as we haven't made a new release of the library yet).

**Comment by charlie9526** [comment]
@jklaise gen_category_map is not worked yet in current library. How to handle that?

**Comment by jklaise** [comment]
@charlie9526 what is the issue, do you have an example that doesn't work?

**Comment by charlie9526** [comment]
The AnchorTabular worked for me when the categorical features are label encoded. Without label encoding an error happen in if np.argmax(predictor(np.zeros([1, len(feature_names)])).shape) == 0:. Now it works after label encoding. Thank you!
