### ISSUE TITLE
Update docstrings

### ISSUE THREAD

**Issue by jklaise** [SeldonIO/alibi#229]
Some docstrings are out of date, some need consolidation. of conventions.

 - CF methods still say they return `dict` instead of `Explanation`.
 - Conventions for referring to instance * features tensors (consistent naming and math notation)
 - Describe `Explanation` object returned consistently, potentially include the keys for each method or as a minimum a link to docs?

**Comment by ascillitoe** [comment]
@RobertSamoilescu @jklaise I thought I would use this issue to track some of the other related issues we are having with docstrings. @RobertSamoilescu is working on some of these in #548.

#### 1) Duplicated class attributes

```python
class TabularSampler:
    """ 
    A sampler that uses an underlying training set to draw records that have a subset of features with
    values specified in an instance to be explained, `X`.

   Attributes
   -------------
   instance_label: Description here.
   """

   instance_label: int

   def __init__(...):
```

This leads to `instance_label` being present twice in the docs for `TabularSampler`. I suspect forcibly removing `undoc_members` from the api rst files would fix this, but it might have other unintended consequences. An easier fix is to do 

```python
class TabularSampler:
    """ 
    A sampler that uses an underlying training set to draw records that have a subset of features with
    values specified in an instance to be explained, `X`.
   """

   instance_label: int  #: Description here.

   def __init__(...):
```

The only issue with this might be when we have inline type hints, as @RobertSamoilescu has discovered we can't have two sets of inline comments e.g. for describing the attribute, and a type hint. For example:

```
attr = {} # type: dict #: A description.
```

does not work. However, we can instead do:

```
attr: dict = {} #: A description.
```

This requires the newer inline type hint, but we might be OK here as this is supported from python 3.6 onwards (https://www.python.org/dev/peps/pep-0526/).

Other options are:

```
#: A description.
attr = {} # type: dict
```

or:

```
attr = {} # type: dict
"""A description."""
```

I think both might work (haven't tested, but they require an extra line).

#### 2) Inconsistency in duplication of return args

In some cases, return descriptions are italicized, and in some cases they are not. For example:

Not italicized: https://docs.seldon.io/projects/alibi/en/latest/api/alibi.explainers.ale.html#alibi.explainers.ale.minimum_satisfied
Italicized: https://docs.seldon.io/projects/alibi/en/latest/api/alibi.explainers.ale.html#alibi.explainers.ale.plot_ale

@RobertSamoilescu has discovered (correct me if wrong!) that the presence of backticks in the description prevents the description being italicized (probably because backticks make the text inside italicized already). However, I suspect the root cause here is actually that the napoleon numpy format doesn't allow for return args with no type specified (https://github.com/sphinx-doc/sphinx/issues/5887). The standard numpy format is:

```
Returns
----------
    result_sum : float
        Sum of numbers.

    result_prod : float
        Product of numbers.
```

So, when we just do something like:

```
Returns
----------
Integer encoded boolean with 1 - each bin has at least `min_bin_points` and 0 otherwise.
```

The description is interpreted as the return argument name instead. In other words, we don't want descriptions to be italicized, we need to do:

```
Returns
----------
arg_name
     Integer encoded boolean with 1 - each bin has at least `min_bin_points` and 0 otherwise.
```

Annoyingly this is also why when we try to have free form descriptions for returns (e.g. when we return dicts or tuples), some parts are italicized. For example:

```
    tuple containing

        - result_sum (float): Sum of numbers
        - result_prod (float): Product of numbers
```

"tuple containing" will be incorrectly italicized as it is interpreted as the return arg name. 

One solution would be to switch to Google style docstrings, as these allow for freeform return descriptions (see https://github.com/sphinx-doc/sphinx/issues/9119 for more discussion). Alternatively we just put up with the slight mismatch in font, or we try to monkey patch something in `conf.py` to change behavior...

**Comment by jklaise** [comment]
My thoughts:

1) Definitely want to avoid duplication, so great you've picked this up. I don't have a strong preference which way to go, both look fine to me. I've got into a habbit of using inline type hints for declaring variables (class or instance) in the class body though within functions I think it's more readable to stick with comments (as you often want to focus on the action being performed).

2) Again, avoid duplication at all cost. I think we can live with slight inconsistencies in the return formatting, it's probably not worth spending time on patching things. We could open a new/tracking issue once this is done to lookout for fixes upstream or potentially changing docstring formats.

**Comment by jklaise** [comment]
Closing this as our docstrings are now in good shape after #548 and #571.
