### ISSUE TITLE
Categorical data not working in Anchor Tabular

### ISSUE THREAD

**Issue by aclarkData** [SeldonIO/alibi#252]
In your example https://docs.seldon.io/projects/alibi/en/stable/examples/anchor_tabular_adult.html, you show how using a categorical map, you can use Anchors on categorical data. However, you pre-encoded the categorical data to numeric in your fetch data command, so in fact, you have a redundant pipeline when you are passing in only numeric data. When I tried to use the Adult dataset straight from Kaggle, for instance, I get some weird errors, such as ValueError: could not convert string to float: '?', when I ran everything the same, accept read in the raw data instead of your fetch command. Please advise

**Comment by jklaise** [comment]
So there are a couple of things going on. First of all, in our `fetch_adult` function you're correct that we turn categorical data from strings into numbers via ordinal encoding, however these are still fundamentally cateforical columns and should not be treated as numeric, hence the one-hot-encoder is stil relevant as it takes the categorical columns (given by `category_map.keys()`) and expands those into one-hot vectors (if you call `preproccessor.fit(X_train).shape` you will get 57 columns after one-hot encoding).

Second, the main reason why you are getting that error is because you're trying to work with numpy arrays that contain both numeric and string data. So you will have to create a numpy array that only has numeric types either as a pre-processing step (as we have done in `fetch_adult`) or as part of the model pipeline (though I haven't checked if this would work). Additionally, you will have to create a new category_map, but this is easy, you can just use the utility function `alibi.utils.data.gen_category_map(X)` where `X` is a pandas dataframe of features (if X is a numpy array then you also need to pass in  a list `categorical_columns` as it's impossible to infer which ones are categorical otherwise).

Let me know if this helps.

**Comment by HeyItsBethany3** [comment]
Hi, I'm having this same issue. 

How do you mean create a numpy array with only numeric types before pre-processing? 

At the moment, I'm one hot encoding the categorical variables as part of a model pipeline, (so when predict(x) is called, it converts the categorical variables in x to be one hot encoded - and changes the order of the features so the categorical variables are at the end). I'm confused about which feature vector to pass in and which category_map because it is different pre-encoded and after. 

I would rather not encode my data beforehand and encode it in the pipeline (when predict is called), so I have an instance format that makes sense and I can work with.

When you encode one categorical feature, say 'A', to ordinal numbers, 'A' will have multiple columns (eg. 2) and then when it's onehot encoded it will have more columns. How do you tell Anchor Tabular that these 2 columns refer to only one categorical feature. 

Thanks so much!

**Comment by jklaise** [comment]
@HeyItsBethany3 what is the format of the categorical variables before one-hot-encoding? What I meant was that the format expected is 1 column per categorical variable and each category is encoded using integers 0,1,...,n-1 (a.k.a. label/ordinal encoding). If your model takes in this format and you have one-hot-encoding as part of your model/pipeline then everything should work as is. If you have some other format (e.g. pandas dataframes with string values for categories) then that is not supported at the moment (you could write a wrapper around your model to conform to the input alibi explainers expect, but this can be messy, e.g. https://github.com/SeldonIO/alibi/issues/364#issuecomment-799370871).

Related, we will soon also support taking in arrays with already one-hot-encoded categorical variables (appreciate this is not your use case!), see #336.

**Comment by HeyItsBethany3** [comment]
Thank you so much! I ordinal encoded the categorical variables and it worked! 
I've been trying to fix this for the last 8 hours so I can't tell you how much I appreciate your quick reply and getting this working, thank you.

I'm having just one more issue: explainer.explain() is not working. I'm running
`explanation = explainer.explain(xTest.iloc[0,:].to_numpy().reshape(1, -1), threshold=0.95)`
where xTest is a dataframe. The error is  "argument of type `numpy.float64' is not iterable`. Do you have any idea why this isn't working?
When using `explanation = explainer.explain(xTest.to_numpy(), threshold=0.95)`, I have the error `Given feature/column names or counts do not match the ones for the data given during fit.` as well. 

Thanks so much for your help.

**Comment by jklaise** [comment]
@HeyItsBethany3 the anchor algorithms operate on single instances only not batch, so there should be no batch dimension (e.g. try removing `reshape(1,-1)`.

**Comment by HeyItsBethany3** [comment]
This gives the same error `argument of type 'numpy.float64' is not iterable`
`xTest.iloc[0,:].to_numpy()` is of the form `[1 .0 2.0 ... ]` (a numpy array with floats) if that helps

**Comment by jklaise** [comment]
Hmm that's a bit strange, is there a stacktrace where it happens inside the library? Also, which columns correspond to categorical variables and what does the `categorical_names` dictionary look like?

**Comment by HeyItsBethany3** [comment]
The category map is `{8: [0.0, 1.0, 2.0]}`

Stacktrace:
<img width="1390" alt="Screenshot 2021-06-04 at 17 44 52" src="https://user-images.githubusercontent.com/24189365/120835706-9442c900-c55c-11eb-99a8-cd5400a2b625.png">

**Comment by jklaise** [comment]
Ah, can you try to cast the category map values to list of ints (instead of floats)? I think that's causing the indexing issue.

**Comment by HeyItsBethany3** [comment]
I've cast it so that the category_map is {8: [0, 1, 2]} and I've cast the categorical column to be an int in the pre-processed data. It's now giving the error `argument of type 'int' is not iterable`. 
I'm not sure if it's relevant but xTest is a dataframe (with ints) and then using .to_numpy() always expresses the numbers in e notation.

**Comment by jklaise** [comment]
Hmm not quite sure what the underlying problem is yet, but what about doing `to_numpy().astype(int)` if the original data is all integers anyway?

**Comment by HeyItsBethany3** [comment]
`to_numpy().astype(int)` gives the same error `argument of type 'int' is not iterable`

`explainer.feature_values` is `{8: [0, 1, 2], 0:['Numerical variable 1 '<= -3', 'Numerical variable 1' > -3'], 1: ... } and so on
It includes all of the variables, even the numerical variables and looks a bit like anchors.

**Comment by jklaise** [comment]
Ah I think I know what the problem is. The `category_names` dictionary must be of type `Dict[int, List[str]]`, i.e. for every categorical variable you provide a list of string names of categories. Because in your example you've provided ints or floats instead, the code processing the display result fails because it tries to do a string search `'<' in self.feature_values...`. It should work if you cast your category map to a list of strings instead.

This is something we should document better as a requirement and validate the category map (potentially attempt to coerce into strings).

**Comment by HeyItsBethany3** [comment]
It works! Thank you so much, I really appreciate your help on this :)

**Comment by jklaise** [comment]
See resolution in #420 .
