### ISSUE TITLE
Assertion error converting OHE variables - counterfactuals guided by prototypes

### ISSUE THREAD

**Issue by HeyItsBethany3** [SeldonIO/alibi#278]
Assertion error when converting one-hot-encoded categorical variable to ordinal encoded variable using counterfactuals guided by prototypes . My raw data point that I want to find a counterfactual for  is of the form [1, 1, 1, 'DebtCon’] 
where the 4th column is the reason for a loan application and take two values (has two categories). 
The cat_vars variable I pass is {4: 2} since the categorical variable is in the 4th column and has 2 categories. My encoded data is of the form [1, 1, 1, 1.0, 0.0].
Is this the wrong format? Do the column labels start at 0? 
![5F1EC78D-9569-451F-9CF7-56AE7A0D9612](https://user-images.githubusercontent.com/24189365/88922021-666b6480-d267-11ea-9722-d4f099e41d97.png)

Also as a side question I’m struggling to understand how to implement the feature_wise feature ranges. 
What would you specify for the ranges of categorical features? What numbers do they get transformed from one hot encoding to? The  minimum and maximum values for categories don’t make much sense to me. 
![Screenshot 2020-07-30 at 13 13 54](https://user-images.githubusercontent.com/24189365/88922037-708d6300-d267-11ea-9d84-dabfde766df1.png)

Many thanks for your help, 
Bethany

**Comment by jklaise** [comment]
For the first question, you're correct, column numbering starts at 0 which is the same as in numpy/python, so `{3:2}` should work.

For the second question, basically every categorical feature gets embedded into numerical space internally, so in your case the 3 numerical features and 1 categorical feature get mapped to a vector of length 4. This means that to specify a `feature_range` you would provide 2 vectors of length 4 (one for minimum, one for maximum) where the first 3 constrain the numerical features and the last one constrains the categorical feature **in the internally embedded numerical space**. Currently it's hard for the user to provide constraints for categorical features because of having to provide this in the embedding space.

However, an appropriate `feature_range` gets automatically calculated in the `fit` step as there is a `update_feature_range=True` argument. So by default if you just want to ensure maximum feature ranges, it works out of the box. In the more advanced use case of constraining feature ranges more than just the min/max, you can do it by passing a custom `feature_range` at least for numerical features but it's more complex for categorical features which we need to fix and provide a more user friendly way of constraining categories (see #175 ).

**Comment by HeyItsBethany3** [comment]
Thank you, this was really helpful. I think my main problem was that my feature_range feature-wise min and max values were not a numpy array and not the right shape, but it's working now. Thank you.
