### ISSUE TITLE
Index Error in CounterFactual.explain(X)

### ISSUE THREAD

**Issue by DashingLine** [SeldonIO/alibi#310]
Hi All, 
I'm getting the error below when trying to use the CounterFactual.explain(X). I'm not sure what to report here to guide the solution for this issue... I'm working with an image classification problem based on RESNET (resolution of 224x244x3), there are three labeled categories. And the execution gives a result... however, I'm not confident in such results after this error message...

```
Could not find upper bound for lambda where no solutions found, setting upper bound to lam_init=0.1
Traceback (most recent call last):
  File "/..../ counterfactual/alibi-env/lib/python3.6/site-packages/alibi/explainers/counterfactual.py", line 530, in _minimize_loss
    ub_ix = np.where(cf_count == 0)[0][-1]  # TODO is 0 robust?
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by jklaise** [comment]
@DashingLine this happens when there is no upper bound to lambda found which results in no counterfactuals found. E.g. if I run the MNIST example with `lam_init=1e-4` and `max_lam_steps`, then the algorithms does a first pass on following range of lambda:
```
[1.e-04 1.e-05 1.e-06 1.e-07 1.e-08 1.e-09 1.e-10 1.e-11 1.e-12 1.e-13]
```
and counts the number of counterfactuals (in 100 gradient steps) found, in this case (internally this is the `cf_count` variable):
```
[ 86. 100. 100. 100. 100. 100. 100. 100. 100. 100.]
```
What the error message is saying is that it can't find an upper bound of lambda for which there are no counterfactuals, so it will just stick with `lam_init=1e-04` as the upper bound.

The found counterfactuals are still valid, but I'll modify the message to be a warning instead (or more likely to put it into `logger.info` for verbose runs) so that it's not so confusing for users.

**Comment by DashingLine** [comment]
Thanks you for you answer !, I'm still a bit confused with the answer... In particular, these two sentences do not seems to go well together...```this happens when there is no upper bound to lambda found which results in no counterfactuals found. ``` and ```The found counterfactuals are still valid```.  
Does this mean that no matter what (high) value will lambda take, there are allways countefactuals ? I am not very familiar with the method, so I'm not sure to understant why is that an issue ? Also, I noticed that the difference in values bettween the original image and the counterfactural is not bigger than 10e-2, which for images does not make much sense... should be that scale up to [0,255] or [0,1] ranges ? any idea on how to do that?

**Comment by jklaise** [comment]
Apologies, I slightly amended the confusing sentence.

The lambda is a multiplier on the distance term in the loss, so the higher the lambda the more important it is that a counterfactual is close to the test instance and less important that it actually results in a different prediction. So with lambda big enough you would expect to not find any counterfactuals anymore (as the instances will be too close to the original). In the method you start with `lam_init` and then do a sweep over `lam_init*10^(-k)` for `k=0,...,max_lam_steps`, so if your `lam_init` isn't very high so that counterfactuals exist for all values of lambda over this sweep then you would get this message.

For the numerical values the CFs are going to be on the same numerical scale as the input, so if input was between [0,1] then the output will generate CFs roughly in the same range. You can always check that the returned CF is an actual CF (by feeding it into the model), but if it wasn't then the library would also print a message that none were found.
