### ISSUE TITLE
Questions regarding to the evaluation of CFPROTO

### ISSUE THREAD

**Issue by Labaien96** [SeldonIO/alibi#368]
Hello,

First of all, I would like to thank you for the work you have done. 
I have some questions about how you do the evaluation. Reading the paper, in table 4, you have made a summary of what class the instances generated with each method belong to. What is not clear to me is that in the test data, in total there are 10.000 instances and in the evaluation you only create around 5.000 counterfactual instances, why is that? On the other hand, in your method it is possible to indicate the class to which you want to change the original sample, the changes in table 4 are made in this way or without indicating the class? If it is possible, I would be grateful if you could upload the script where you do the evaluation of the methods. 

Thanks in advance.

**Comment by jklaise** [comment]
Hi, thanks for your questions.

At the time of the experiment we were running on a limited compute budget so we stopped the experiments roughly mid-way through the test-set. We were running the different loss functions A-D in parallel on the whole test set in the same sequence of instances but due to the different compute demands the resulting total numbers are different as some methods processed more instances than others.

The table reports unconstrained change of class, i.e. we ran each method until it generated a counterfactual different from the original class.

Concerning the analysis scripts, I'm not sure they will be very helpful as we have a script to run CF algorithm in parallel and then some notebooks for analysing the results. Is there any part of the evaluation procedure in particular that we can help clarify?

**Comment by Labaien96** [comment]
Thank you for the clarification. Don't worry, I wanted to make different comparisons between methods in terms of IM1 and IM2 and I was asking just to make it clear to me how you did the evaluation. Thank you!

**Comment by Labaien96** [comment]
Another brief question Janis. When using cfproto, I have followed the guidelines in the alibi guide, but I am not sure which variant of cfproto is used when running this:
```
shape = (1,) + x_train.shape[1:]
gamma = 100.
theta = 100.
c_init = 1.
c_steps = 2
max_iterations = 1000
feature_range = (x_train.min(),x_train.max())

cf = CounterFactualProto(cnn, shape, gamma=gamma, theta=theta,
                         ae_model=ae, enc_model=encoder, max_iterations=max_iterations,
                         feature_range=feature_range, c_init=c_init, c_steps=c_steps)
cf.fit(x_train)

explanation_cfproto = cf.explain(X, k=5, k_type='mean')

```

From A to F, which one am I using? Which one do you think we should use?

**Comment by jklaise** [comment]
@Labaien96 for the configuration you've showed this would correspond to D in the paper (i.e. all losses turned on).

As for what configuration is best is really dependent on your use case. For the in-distributioness property `L_proto` is pretty much necessary. `L_AE` should also help to respect the overall data distribution. We also showed in the paper that at least on MNIST the configuration D resulted in the quickest counterfactuals measured by the number of gradient steps.

**Comment by Labaien96** [comment]
Thank you @jklaise. I am working with the MNIST use case, so I will use that configuration.
