### ISSUE TITLE
TreeShap does not support Gradient Boosting Sklearn model

### ISSUE THREAD

**Issue by HeyItsBethany3** [SeldonIO/alibi#384]
I'm using a simple sklearn model GradientBoostingClassifier but when I run explainer.fit(), I am getting the error:

`Model type not yet supported by TreeExplainer`

I have tried changing the way explainer is defined, trying:
`explainer = TreeShap(model)`
`explainer = TreeShap(model, model_output='raw', task='classification', feature_names=featureNames)`

I have also tried creating the sklearn model using both 
`GradientBoostingClassifier(loss='deviance')` and `GradientBoostingClassifier(loss='exponential')`

The documentation says that sklearn models are supported. Do you have any idea why this is not working? 

Thanks for your help. :)

**Comment by jklaise** [comment]
How many output classes do you have? It seems like `GradientBoostingClassifier` is only supported for binary classifiers: https://github.com/slundberg/shap/blob/0235a7ecb3260202356a7e7e9ae56a9586c4462b/shap/explainers/_tree.py#L763-L781

**Comment by HeyItsBethany3** [comment]
I have a binary classification problem, but I have solved the issue now, thank you - the way I defined my model was wrong. 
Now I am getting an output but with the warning 
`Predictor returned a scalar value. Ensure the output represents a probability or decision score as opposed to a classification label!` 
Do you know why this is? I am passing in the model, not a function. Is it implicitly calling the predict method on GradientBoostingClassifier instead of the predict_proba method? 

Thanks so much for your help and speedy replies :)

**Comment by jklaise** [comment]
@HeyItsBethany3 glad you solved your problem!

I had a look at what's happening to raise that warning which is coming from `alibi`. I believe this is slightly misleading on our part in this case as everything is actually functioning as expected. Basically the `shap` library is internally checking the output dimension of the base models inside `GradientBoostingClassifier` which happens to be 1 because in the binary case the base classifiers predict the log-odds of one class only. This is all as expected but we output a warning which is misleading in this particular case. I'll rethink how to improve the warning so that it's output when it's relevant (though it may be difficult to cover all scenarios).
