### ISSUE TITLE
Issue with numpy version

### ISSUE THREAD

**Issue by nvpdpoem** [SeldonIO/alibi#445]
When I install alibi (both via pip install alibi or by building from source), in both cases, when I execute `import alibi`, I get the following error.
`RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd`
I am using numpy version 1.19.5 and can't update because my tensorflow version explicitly requires 1.19.2 or closer.

**Comment by jklaise** [comment]
This is an issue because of the `shap` dependency which is misconfigured upstream (see https://github.com/slundberg/shap/pull/1802#issuecomment-846299228 for more information). If you're not using `shap` then there is no issue, if you are, then you should re-install `shap` (disable caching for `pip`) so it is built against `numpy` 1.19.x in your environment. In the [Installation](https://github.com/SeldonIO/alibi#installation-and-usage) section we mention that `shap` support requires a two-stage command.

**Comment by nvpdpoem** [comment]
I am very sorry for the delayed response.
This seems to have worked. Thanks a lot!
