### ISSUE TITLE
Report test duration in CI

### ISSUE THREAD

**Issue by ascillitoe** [SeldonIO/alibi#840]
To identify long-running tests during CI, it would be helpful for overly long-running tests to report their duration. This could be achieved by:

1. Add a timeout with `pytest-timeout`, so that tests that take longer than a certain (relatively generous) duration would simply be killed. Long-running tests would then be reported as failed.
2. Add a pytest hook to report duration after each test. Something like [this](https://stackoverflow.com/questions/61644097/pytest-hook-to-access-durations).

As noted by @jklaise , with option 2. a minimum duration threshold would be required to avoid cluttering the output.

**Comment by jklaise** [comment]
Just for context, we should also do the command line argument `--durations=50` (report the top 50 long running tests at the end of the test suite). The reason we're considering a hook (or use of a timeout) is to identify long running tests before the test suite has finished. This is required because our MacOS CI tests frequently time out and take almost 6h to run (compared to ~1h on other OSes).

**Comment by jk** [comment]
@ascillitoe I'm not @jklaise

**Comment by ascillitoe** [comment]
> @ascillitoe I'm not @jklaise

Apologies!

**Comment by jklaise** [comment]
Closing as implemented in #849.
